<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>name</key>
<string>Log file</string>
<key>scopeName</key>
<string>text.log</string>
<key>fileTypes</key>
<array>
<string>log</string>
<string>log.dev</string>
</array>
<key>uuid</key>
<string>e0bea9c9-c772-4f31-b136-716e2b2fafcd</string>
<key>patterns</key>
<array>
<dict>
<key>name</key>
<string>meta.log.date</string>
<key>comment</key>
<string>Date</string>
<key>match</key>
<string>\d{4}\-(\d{2}\-\d{2}) (\d{2}:\d{2}):\d{2}</string>
<key>captures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.log.date.day</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>meta.log.date.time</string>
</dict>
</dict>
</dict>
<dict>
<key>name</key>
<string>meta.log.error</string>
<key>comment</key>
<string>Error output</string>
<key>match</key>
<string>^.+\n</string>
</dict>
<dict>
<key>name</key>
<string>meta.log.status.error</string>
<key>comment</key>
<string>Error</string>
<key>match</key>
<string>\bERROR \d{3}</string>
</dict>
<dict>
<key>name</key>
<string>meta.log.status.success</string>
<key>comment</key>
<string>Success</string>
<key>match</key>
<string>\bSUCCESS \d{3}</string>
</dict>
<dict>
<key>name</key>
<string>meta.log.status.info</string>
<key>comment</key>
<string>Information</string>
<key>match</key>
<string>\bINFO (\d{3}|STREAM)</string>
</dict>
<dict>
<key>name</key>
<string>meta.log.resource</string>
<key>match</key>
<string>(?!\[.+\])([^\s\/]+)?(\/\S*)</string>
<key>captures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.log.resource.host</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>meta.log.resource.path</string>
</dict>
</dict>
</dict>
<dict>
<key>name</key>
<string>meta.log.data</string>
<key>match</key>
<string>\[(.*)\] \[(\d+\.\d+\.\d+\.\d+)\] \[(.*)\]$</string>
<key>captures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.log.data.message</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>meta.log.data.ip</string>
</dict>
<key>3</key>
<dict>
<key>name</key>
<string>meta.log.data.ua</string>
</dict>
</dict>
</dict>
<dict>
<key>name</key>
<string>meta.log.pair</string>
<key>match</key>
<string>(\S+)=(\S+)</string>
<key>captures</key>
<dict>
<key>1</key>
<dict>
<key>name</key>
<string>meta.log.pair.key</string>
</dict>
<key>2</key>
<dict>
<key>name</key>
<string>meta.log.pair.value</string>
</dict>
</dict>
</dict>
</array>
</dict>
</plist>
